//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 28/08/2014 19:49:21
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------


namespace CORE.Auth.Entidades

{

    /// <summary>
    /// There are no comments for Model.ISAGrupoModulo in the schema.
    /// </summary>
    public partial class ISAGrupoModulo    {

        public ISAGrupoModulo()
        {
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for CDGRUPOUSUA in the schema.
        /// </summary>
        public virtual string CDGRUPOUSUA
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CDSISTINFO in the schema.
        /// </summary>
        public virtual string CDSISTINFO
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CDMODUSISTINFO in the schema.
        /// </summary>
        public virtual string CDMODUSISTINFO
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ICACESALTR in the schema.
        /// </summary>
        public virtual string ICACESALTR
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ICACESCONS in the schema.
        /// </summary>
        public virtual string ICACESCONS
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ICACESEXCL in the schema.
        /// </summary>
        public virtual string ICACESEXCL
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ICACESINCS in the schema.
        /// </summary>
        public virtual string ICACESINCS
        {
            get;
            set;
        }


        #endregion
    }

}
