//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 28/08/2014 19:49:21
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Data.Entity.ModelConfiguration;
using CORE.Auth.Entidades;

namespace CORE.Auth.Mapeamentos
{

    public class ISAGrupoModuloConfiguration : EntityTypeConfiguration<ISAGrupoModulo>
    {

        public ISAGrupoModuloConfiguration()
        {
            this
                .HasKey(p => new { p.CDGRUPOUSUA, p.CDSISTINFO, p.CDMODUSISTINFO })
                .ToTable("ISA_GRUPO_MODU_SIST", "ADM_ISA");
            // Properties:
            this
                .Property(p => p.CDGRUPOUSUA)
                    .HasColumnName(@"CD_GRUPO_USUA")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.CDSISTINFO)
                    .HasColumnName(@"CD_SIST_INFO")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.CDMODUSISTINFO)
                    .HasColumnName(@"CD_MODU_SIST_INFO")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.ICACESALTR)
                    .HasColumnName(@"IC_ACES_ALTR")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.ICACESCONS)
                    .HasColumnName(@"IC_ACES_CONS")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.ICACESEXCL)
                    .HasColumnName(@"IC_ACES_EXCL")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("varchar2");
            this
                .Property(p => p.ICACESINCS)
                    .HasColumnName(@"IC_ACES_INCS")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("varchar2");
        }
    }
}
